# EverLeaf v180 gameplay UI visual overlay.
# Uses only existing v83 runtime paths/features. TRADE/FM (StatusBar/BtNPT) is intentionally preserved for later.
# Donor images are first converted to v83/GMS format with modern canvas links materialized.

image:BuffIcon.img
image:GuildBBS.img
image:GuildMark.img
image:ChatBalloon.img
image:NameTag.img

# Modernize the status bar while preserving the current TRADE button artwork until FM visual direction is approved.
property:StatusBar.img/base
property:StatusBar.img/gauge
property:StatusBar.img/BtShop
property:StatusBar.img/BtMenu
property:StatusBar.img/BtShort
property:StatusBar.img/BtWhisper
property:StatusBar.img/BtClaim
property:StatusBar.img/EquipKey
property:StatusBar.img/InvenKey
property:StatusBar.img/StatKey
property:StatusBar.img/SkillKey
property:StatusBar.img/KeySet
property:StatusBar.img/QuickSlot
property:StatusBar.img/QuickSlotD
property:StatusBar.img/key
property:StatusBar.img/number
property:StatusBar.img/FontMemo

property:Basic.img/Cursor
property:Basic.img/CheckBox
property:Basic.img/HScr
property:Basic.img/HScr2
property:Basic.img/HScr3
property:Basic.img/HScr4
property:Basic.img/HScr5
property:Basic.img/VScr
property:Basic.img/VScr2
property:Basic.img/VScr3
property:Basic.img/VScr4
property:Basic.img/VScr5
property:Basic.img/VScr8
property:Basic.img/BtOK
property:Basic.img/BtCancel
property:Basic.img/BtYes
property:Basic.img/BtYes2
property:Basic.img/BtNo
property:Basic.img/BtNo2
property:Basic.img/BtComboBox
property:Basic.img/Notice
property:Basic.img/Notice2
property:Basic.img/Notice3
property:Basic.img/Notice4
property:Basic.img/YesNo
property:Basic.img/YesNo2
property:Basic.img/YesNo3
property:Basic.img/Tab
property:Basic.img/Tab2
property:Basic.img/Tab3
property:Basic.img/Tab4
property:Basic.img/Tab5
property:Basic.img/ItemNo
property:Basic.img/dcMark
property:Basic.img/LevelNo
property:Basic.img/BtMin
property:Basic.img/BtMin2
property:Basic.img/BtMax
property:Basic.img/BtMax2
property:Basic.img/BtOK2
property:Basic.img/BtCancel2
property:Basic.img/BtUP
property:Basic.img/BtDown
property:Basic.img/BtHide
property:Basic.img/BtHide2
property:Basic.img/BtClose
property:Basic.img/BtClose2
property:Basic.img/BtClaim
property:Basic.img/ComboBox
property:Basic.img/ComboBox2
property:Basic.img/ComboBox3
property:Basic.img/BtOK3
property:Basic.img/BtCancel3
property:Basic.img/BtQGiveup
property:Basic.img/KeyDownBar
property:Basic.img/BtSend
property:Basic.img/BtReceive
property:Basic.img/BtDel
property:Basic.img/icon
property:Basic.img/BtCoin
property:Basic.img/Tab6
property:Basic.img/Tab7
property:Basic.img/BtDecide
property:Basic.img/KeyDownBar1
property:Basic.img/BtHide3
property:Basic.img/BtMacro
property:Basic.img/VScr6
property:Basic.img/HScr6
property:Basic.img/ComboBox4
property:Basic.img/PQuestRank
property:Basic.img/ShowLevel
property:Basic.img/Notice5
property:Basic.img/ComboBox5

# Existing v83 windows whose complete path trees are present in v180.
property:UIWindow.img/UserList
property:UIWindow.img/MiniMap
property:UIWindow.img/ToolTip
property:UIWindow.img/Minigame
property:UIWindow.img/KeyConfig
property:UIWindow.img/ShortCut
property:UIWindow.img/Skill
property:UIWindow.img/Stat
property:UIWindow.img/Item
property:UIWindow.img/Equip
property:UIWindow.img/Channel
property:UIWindow.img/Quest
property:UIWindow.img/QuestAlarm
property:UIWindow.img/GameMenu
property:UIWindow.img/UserInfo
property:UIWindow.img/Messenger
property:UIWindow.img/Trunk
property:UIWindow.img/WorldMap

# Selective Cash Shop/preview areas with 100% v83 path coverage in v180.
property:CashShop.img/CSChar
property:CashShop.img/CSTab
property:CashShop.img/CashItem
property:CashShop.img/PrepaidCashItem
property:CashShop.img/NewItem
property:CashShop.img/GuideWords
property:CashShop.img/CSIcon
property:CashShop.img/CSDiscount
property:CashShop.img/CSChangeName
property:CashShop.img/CSTransferWorld
property:CashShop.img/CSWebMsg
property:CashShop.img/CSGift
property:CashShop.img/CS3thEvent
