// <auto-generated />
namespace EverLeaf.Launcher.Properties;

[global::System.Runtime.CompilerServices.CompilerGenerated]
[global::System.CodeDom.Compiler.GeneratedCode("SettingsSingleFileGenerator", "1.0.0.0")]
internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
{
    private static readonly Settings defaultInstance =
        (Settings)Synchronized(new Settings());

    public static Settings Default => defaultInstance;

    [global::System.Configuration.UserScopedSetting]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Configuration.DefaultSettingValue("")]
    public string RememberedUsername
    {
        get => (string)this[nameof(RememberedUsername)];
        set => this[nameof(RememberedUsername)] = value;
    }
}
