const categories=[
  {key:'classes',label:'Jobs & Classes',description:'Classic job families, advancement paths, and EverLeaf class notes.'},
  {key:'progression',label:'Progression',description:'Leveling, post-200 progression, survivability, and long-term systems.'},
  {key:'systems',label:'EverLeaf Systems',description:'Server-specific quality-of-life and gameplay systems.'},
  {key:'rewards',label:'NX & Rewards',description:'Non-P2W reward sources, voting, playtime, and custom NX systems.'},
  {key:'launcher',label:'Launcher & Client',description:'Launcher-managed updates, client compatibility, repair, and player setup.'},
  {key:'world',label:'World & Travel',description:'Channels, transportation, maps, NPCs, and world behavior.'},
  {key:'content',label:'Content Integrity',description:'NPCs, maps, custom content, data quality, and release consistency.'},
];

const sourceDocs={
  project:'PROJECT-DESIGN.md',
  systems:'SERVER-SYSTEMS.md',
  cms:'CMS-WEB.md',
  launcher:'LAUNCHER-PATCHER.md',
  qol:'QOL-KNOWN-ISSUES.md',
  maps:'NPC-MAPS.md',
  nx:'CUSTOM-NX-CASH.md'
};

const entry=(data)=>({verification:'Preserved EverLeaf decision',sourceDoc:'',...data});

const entries=[
  entry({slug:'enhanced-classic',category:'systems',title:'What is Enhanced Classic?',eyebrow:'EVERLEAF IDENTITY',summary:'EverLeaf keeps the recognizable MapleStory v83 foundation while deliberately modernizing progression, quality-of-life, infrastructure, and selected systems.',status:'EverLeaf Modified',source:'EverleafMS / PROJECT-DESIGN',sourceDoc:sourceDocs.project,tags:['v83','classic','qol','design'],sections:[['Core philosophy','Classic does not mean preserving every historical inconvenience. EverLeaf keeps familiar maps, classes, bosses, quests, items, and progression identity while improving avoidable friction.'],['Intentional differences','Current design includes level 250 progression, post-200 systems, an HP-washing replacement, faster transportation, Trade button to Free Market, custom NX/rewards, Pet Vac, custom content, widescreen support, and modern launcher/web tooling.'],['Fair-play direction','EverLeaf is donation-supported and non-pay-to-win. Paid support should not become mandatory competitive power or a gate to normal progression.']]}),
  entry({slug:'server-authority',category:'systems',title:'Server Authority',eyebrow:'SECURITY & GAMEPLAY',summary:'Economic, account, progression, reward, and ownership decisions remain authoritative on the EverLeaf server even when the client and website are customized.',status:'EverLeaf Principle',source:'EverleafMS / PROJECT-DESIGN + SERVER-SYSTEMS',sourceDoc:sourceDocs.systems,tags:['security','server','authority','economy'],sections:[['Authoritative systems','Authentication, level/EXP, reward grants, NX ownership, item ownership, trade/drop permissions, vote verification, and map migration authorization remain server-side.'],['Client boundary','The client handles display, assets, and input, but client-visible state must not be trusted as economic or account authorization.'],['Website boundary','The CMS may display or request controlled operations, but it should not become a second gameplay authority.']]}),
  entry({slug:'level-250-progression',category:'progression',title:'Level 250 Progression',eyebrow:'PROGRESSION',summary:'EverLeaf extends the classic v83 progression curve beyond level 200 with server-authoritative level and EXP handling through level 250.',status:'EverLeaf Modified',source:'EverleafMS / SERVER-SYSTEMS',sourceDoc:sourceDocs.systems,tags:['level 250','exp','post-200'],sections:[['Level cap','EverLeaf targets level 250 instead of the stock v83 level-200 cap. At level 250, terminal/max-level behavior applies.'],['Post-200 EXP','The preserved server policy records the legacy level-200 requirement at 1,697,021,059 EXP, level 201 at 1,700,000,000, then increases requirements by 6,250,000 per level until approaching the server safety cap.'],['Authority','Level and EXP calculations remain server-authoritative. Client UI compatibility for post-200 values is a separate display concern.']]}),
  entry({slug:'hp-washing-replacement',category:'progression',title:'HP Washing Replacement',eyebrow:'CHARACTER PROGRESSION',summary:'EverLeaf is designed so mandatory legacy INT washing is not the expected route to viable endgame survivability.',status:'EverLeaf Modified',source:'EverleafMS / SERVER-SYSTEMS',sourceDoc:sourceDocs.systems,tags:['hp washing','hp','survivability'],sections:[['Design goal','Character survivability should come from an intentional server-designed progression path rather than requiring players to plan years of legacy INT washing.'],['What this means','Quality-of-life removes the historical burden without making survivability meaningless. Exact progression mechanics should always be documented as the implementation evolves.']]}),
  entry({slug:'adventurer-jobs',category:'classes',title:'Adventurer Job Families',eyebrow:'JOBS & CLASSES',summary:'Beginner advances into the five classic Adventurer families: Warrior, Magician, Bowman, Thief, and Pirate.',status:'Classic v83',verification:'Classic reference + EverLeaf UI mapping',source:'EverLeaf class reference',sourceDoc:'class reference',tags:['warrior','magician','bowman','thief','pirate','beginner'],sections:[['Warrior','Fighter → Crusader → Hero; Page → White Knight → Paladin; Spearman → Dragon Knight → Dark Knight.'],['Magician','Fire/Poison and Ice/Lightning Wizard paths advance through Mage to Arch Mage; Cleric advances to Priest and Bishop.'],['Bowman','Hunter → Ranger → Bow Master; Crossbowman → Sniper → Marksman.'],['Thief','Assassin → Hermit → Night Lord; Bandit → Chief Bandit → Shadower.'],['Pirate','Brawler → Marauder → Buccaneer; Gunslinger → Outlaw → Corsair.']]}),
  entry({slug:'trade-button-free-market',category:'systems',title:'Trade Button → Free Market',eyebrow:'QUALITY OF LIFE',summary:'EverLeaf repurposes the classic Trade/MTS-style button as a convenient route to the Free Market.',status:'EverLeaf Modified',source:'EverleafMS / SERVER-SYSTEMS',sourceDoc:sourceDocs.systems,tags:['free market','trade','qol'],facts:[['Destination','910000000'],['Owner','Server handler']],sections:[['Destination','The intended destination is Free Market map 910000000.'],['How it works','The server-side EnterMTS handler owns the behavior and applies the required guards. A dedicated client patch is not inherently required for the basic button-to-FM behavior.']]}),
  entry({slug:'pet-vac',category:'systems',title:'Pet Vac',eyebrow:'EVERLEAF FEATURE',summary:'Pet Vac is part of the intended EverLeaf feature set and spans both client presentation and server-authoritative item pickup rules.',status:'EverLeaf System',source:'EverleafMS / SERVER-SYSTEMS',sourceDoc:sourceDocs.systems,tags:['pet vac','pets','items'],sections:[['System boundary','Pet Vac touches client packets, pet state, map item pickup, ownership validation, and anti-abuse behavior. It should be treated as a subsystem rather than a simple cosmetic toggle.'],['Authority','Item ownership and pickup authorization remain server-side even when client behavior is customized.']]}),
  entry({slug:'rooted-content',category:'content',title:'Rooted Content',eyebrow:'CUSTOM CONTENT',summary:'Rooted is an EverLeaf content family that includes Rooted Zakum, materials, and related encounters.',status:'EverLeaf Custom',source:'EverleafMS / SERVER-SYSTEMS',sourceDoc:sourceDocs.systems,tags:['rooted','zakum','boss','custom'],sections:[['Known scope','The durable library currently records Rooted Zakum, Rooted materials, and Rooted encounters as intended EverLeaf systems.'],['Wiki expansion','As mechanics are validated, this page will expand into requirements, encounters, drop tables, materials, and progression links.']]}),
  entry({slug:'nx-reward-sources',category:'rewards',title:'NX Reward Sources',eyebrow:'FAIR REWARDS',summary:'EverLeaf distributes NX through repeatable gameplay and verified community actions while keeping reward delivery server-authoritative.',status:'EverLeaf Modified',source:'EverleafMS / SERVER-SYSTEMS',sourceDoc:sourceDocs.systems,tags:['nx','vote','playtime','daily'],facts:[['Daily reward','1,000 NX'],['7-day streak','+1,000 NX'],['Playtime','500 NX / 30 min'],['Playtime daily cap','2,000 NX'],['Verified vote','1,500 NX']],sections:[['Safety model','Reward processing is designed around validation, transactional handling, idempotency, and abuse caps so retries cannot silently double-grant currency.'],['Non-P2W principle','NX systems should support cosmetics, convenience, and fair rewards without becoming mandatory competitive progression.']]}),
  entry({slug:'reward-delivery-safety',category:'rewards',title:'Reward Delivery Safety',eyebrow:'REWARD PIPELINE',summary:'EverLeaf reward delivery is designed to be verifiable, retry-safe, and resistant to double grants or client-side spoofing.',status:'EverLeaf Principle',source:'EverleafMS / SERVER-SYSTEMS',sourceDoc:sourceDocs.systems,tags:['rewards','idempotency','vote','security'],sections:[['Validation first','Vote and other external rewards must be verified before currency is granted.'],['Retry safety','Transactional and idempotent processing means a retried request should not silently grant the same reward twice.'],['Abuse controls','Caps and server-side ownership checks remain part of the reward model.']]}),
  entry({slug:'everleaf-launcher',category:'launcher',title:'EverLeaf Launcher',eyebrow:'PLAYER SETUP',summary:'The launcher is the intended way to install, verify, repair, update, and start EverLeaf without manually maintaining client files.',status:'EverLeaf System',source:'EverleafMS / LAUNCHER-PATCHER + CMS-WEB',sourceDoc:sourceDocs.launcher,tags:['launcher','patcher','updates','client'],sections:[['Player workflow','Players should launch EverLeaf through the launcher rather than running the client executable directly. The launcher owns update and integrity workflows.'],['Release management','Website downloads should reference versioned launcher/client releases instead of ad-hoc mutable files.'],['Future integration','The CMS can surface release manifests, current version, patch notes, rollout state, and launcher health without exposing private deployment secrets.']]}),
  entry({slug:'launcher-repair-updates',category:'launcher',title:'Launcher Repair & Updates',eyebrow:'PATCHING',summary:'EverLeaf uses a manifest-driven patching direction with staged downloads, hash verification, safe activation, and recovery from interrupted updates.',status:'EverLeaf Design',source:'EverleafMS / LAUNCHER-PATCHER',sourceDoc:sourceDocs.launcher,tags:['launcher','repair','manifest','hash','patch'],sections:[['Safe patching','The intended flow compares managed files to a release manifest, downloads only what changed, stages replacements, verifies cryptographic hashes, and activates only validated files.'],['Repair mode','Repair should detect missing or corrupt managed files and redownload them without destroying unrelated user files.'],['Failure recovery','Partial updates should not leave a half-old/half-new client. Staging and rollback state are part of the design.']]}),
  entry({slug:'launcher-first-play',category:'launcher',title:'Why Use the Launcher?',eyebrow:'PLAYER EXPERIENCE',summary:'Starting EverLeaf through the launcher is intentional: it keeps game files current and prevents common direct-client launch problems.',status:'Player Guide',source:'EverleafMS / QOL-KNOWN-ISSUES + LAUNCHER-PATCHER',sourceDoc:sourceDocs.qol,tags:['launcher','play','client','updates'],sections:[['Expected flow','Open the launcher, let it verify or patch files, then use Play to start the client.'],['Direct EXE launches','Players may naturally try to run EverLeaf.exe directly. That is treated as a distribution and UX problem, not evidence that the game server is broken.'],['Why it matters','The launcher is the controlled entry point for version checks, repair, update safety, and launch coordination.']]}),
  entry({slug:'widescreen-support',category:'launcher',title:'Widescreen & Resolution Support',eyebrow:'CLIENT EXPERIENCE',summary:'EverLeaf supports widescreen work, but larger resolutions are only considered correct when rendering, UI placement, and input geometry all agree.',status:'EverLeaf Client',source:'EverleafMS / QOL-KNOWN-ISSUES',sourceDoc:sourceDocs.qol,tags:['widescreen','resolution','ui','client'],sections:[['More than render size','Successful larger rendering is not enough. UI placement, input hitboxes, effects, boss UI, login, Cash Shop, Dojo, and special maps also need validation.'],['Quality rule','Resolution support should be tested as a complete interaction system rather than a collection of isolated hardcoded coordinates.']]}),
  entry({slug:'custom-ui-layer',category:'launcher',title:'EverLeaf UI Layer',eyebrow:'CLIENT UI',summary:'EverLeaf uses EverLeaf_UI.wz as a custom UI/resource layer and favors coherent layout ownership over scattered coordinate patches.',status:'EverLeaf Client',source:'EverleafMS / QOL-KNOWN-ISSUES',sourceDoc:sourceDocs.qol,tags:['ui','wz','client','layout'],sections:[['Custom layer','EverLeaf_UI.wz is the project custom UI/resource layer.'],['Layout direction','New UI work should prefer owner-level layout systems instead of accumulating unrelated hardcoded positions that drift at different resolutions.']]}),
  entry({slug:'world-channels',category:'world',title:'World Channels',eyebrow:'WORLD TOPOLOGY',summary:'EverLeaf channel information should always come from the authoritative live configuration instead of being independently hardcoded into the website.',status:'Live-derived',verification:'Architecture rule from preserved incident',source:'EverleafMS / CMS-WEB + SERVER-SYSTEMS',sourceDoc:sourceDocs.cms,tags:['channels','world','status'],sections:[['Why this matters','A historical website display drifted because it showed a channel count from older configuration. The durable rule is to derive channel/world information from one authoritative source.'],['Current UI rule','Public status can show world/channel availability and player count, but should avoid exposing private host details.']]}),
  entry({slug:'fast-transportation',category:'world',title:'Faster Transportation',eyebrow:'QUALITY OF LIFE',summary:'EverLeaf deliberately reduces long legacy travel waits instead of preserving them purely for nostalgia.',status:'EverLeaf Modified',source:'EverleafMS / SERVER-SYSTEMS',sourceDoc:sourceDocs.systems,tags:['travel','transport','qol'],sections:[['Design direction','Previously preserved policy uses approximately one-second or instant-style travel for relevant legacy transports.'],['Reasoning','The goal is to remove waiting that adds little gameplay value while preserving the world, destinations, and progression around travel.']]}),
  entry({slug:'npc-map-integrity',category:'content',title:'NPC & Map Integrity',eyebrow:'WORLD DATA QUALITY',summary:'EverLeaf tracks misplaced and missing NPCs as a repository-wide content-integrity problem rather than treating each report as an isolated map bug.',status:'Known Audit Area',verification:'Preserved known issue and audit policy',source:'EverleafMS / NPC-MAPS',sourceDoc:sourceDocs.maps,tags:['npc','maps','audit','content'],sections:[['What gets checked','Presence alone is not enough. Important NPCs need the correct map, coordinates, foothold, facing, script, and prerequisite behavior.'],['Related systems','NPC drift can reveal wider issues in portals, reactors, mobs, shops, quests, and map scripts.'],['EverLeaf deviations','Transport and custom-content changes must be distinguished from accidental drift so intentional QoL is not reverted to vanilla by mistake.']]}),
  entry({slug:'custom-nx-pipeline',category:'content',title:'Custom NX Content Pipeline',eyebrow:'CUSTOM CONTENT',summary:'EverLeaf treats custom NX and Cash items as versioned game assets that must stay consistent across client WZ data, server data, strings, Cash Shop records, and launcher releases.',status:'EverLeaf Design',source:'EverleafMS / CUSTOM-NX-CASH',sourceDoc:sourceDocs.nx,tags:['nx','cash shop','wz','items','content pipeline'],sections:[['Canonical content source','The client WZ content is the canonical item-content source. Matching server outputs should be derived from the same validated source whenever possible.'],['Multiple layers','Item definition, Commodity/SN listing, packages, Cash Inventory behavior, strings, visuals, and per-instance ownership are separate concerns that must not be conflated.'],['Release discipline','A custom item is not release-complete until required client assets are validated, server data agrees, hashes/manifests are generated, and the launcher can safely distribute the change.']]}),
  entry({slug:'custom-item-id-discipline',category:'content',title:'Custom Item ID Discipline',eyebrow:'CONTENT GOVERNANCE',summary:'Custom item IDs are structural and should be permanently tracked rather than treated as disposable labels.',status:'EverLeaf Design',source:'EverleafMS / CUSTOM-NX-CASH',sourceDoc:sourceDocs.nx,tags:['items','ids','nx','registry'],sections:[['Category-correct IDs','Custom items should remain inside the correct MapleStory item/category family so range-derived behavior stays predictable.'],['Permanent registry','Allocated, retired, experimental, and reserved IDs should remain recorded with donor relationships, WZ paths, release state, and Cash Shop references.'],['No silent reuse','An ID that has existed in a released build should not be recycled for an unrelated meaning.']]})
];

const bySlug=new Map(entries.map(item=>[item.slug,item]));
function searchEntries(query='',category='all'){
  const q=String(query||'').trim().toLowerCase();
  return entries.filter(item=>{
    if(category&&category!=='all'&&item.category!==category)return false;
    if(!q)return true;
    const hay=[item.title,item.summary,item.status,item.source,item.sourceDoc,item.verification,...(item.tags||[]),...(item.sections||[]).flat(),...(item.facts||[]).flat()].join(' ').toLowerCase();
    return hay.includes(q);
  });
}
function sourceCoverage(){
  return Object.values(sourceDocs).map(doc=>({doc,count:entries.filter(item=>item.sourceDoc===doc).length})).sort((a,b)=>b.count-a.count||a.doc.localeCompare(b.doc));
}
module.exports={categories,entries,bySlug,searchEntries,sourceDocs,sourceCoverage};
