const categories=[
  {key:'classes',label:'Jobs & Classes',description:'Classic job families, advancement paths, and EverLeaf class notes.'},
  {key:'progression',label:'Progression',description:'Leveling, post-200 progression, survivability, and long-term systems.'},
  {key:'systems',label:'EverLeaf Systems',description:'Server-specific quality-of-life and gameplay systems.'},
  {key:'rewards',label:'NX & Rewards',description:'Non-P2W reward sources, voting, playtime, and custom NX systems.'},
  {key:'launcher',label:'Launcher & Client',description:'Launcher-managed updates, client compatibility, and player setup.'},
  {key:'world',label:'World & Travel',description:'Channels, transportation, maps, NPCs, and world behavior.'},
];
const entries=[
  {slug:'enhanced-classic',category:'systems',title:'What is Enhanced Classic?',eyebrow:'EVERLEAF IDENTITY',summary:'EverLeaf keeps the recognizable MapleStory v83 foundation while deliberately modernizing progression, quality-of-life, infrastructure, and selected systems.',status:'EverLeaf Modified',source:'EverleafMS / PROJECT-DESIGN',tags:['v83','classic','qol','design'],sections:[['Core philosophy','Classic does not mean preserving every historical inconvenience. EverLeaf keeps familiar maps, classes, bosses, quests, items, and progression identity while improving avoidable friction.'],['Intentional differences','Current design includes level 250 progression, post-200 systems, an HP-washing replacement, faster transportation, Trade button to Free Market, custom NX/rewards, Pet Vac, custom content, widescreen support, and modern launcher/web tooling.'],['Fair-play direction','EverLeaf is donation-supported and non-pay-to-win. Paid support should not become mandatory competitive power or a gate to normal progression.']]},
  {slug:'level-250-progression',category:'progression',title:'Level 250 Progression',eyebrow:'PROGRESSION',summary:'EverLeaf extends the classic v83 progression curve beyond level 200 with server-authoritative level and EXP handling through level 250.',status:'EverLeaf Modified',source:'EverleafMS / SERVER-SYSTEMS',tags:['level 250','exp','post-200'],sections:[['Level cap','EverLeaf targets level 250 instead of the stock v83 level-200 cap. At level 250, terminal/max-level behavior applies.'],['Post-200 EXP','The preserved server policy records the legacy level-200 requirement at 1,697,021,059 EXP, level 201 at 1,700,000,000, then increases requirements by 6,250,000 per level until approaching the server safety cap.'],['Authority','Level and EXP calculations remain server-authoritative. Client UI compatibility for post-200 values is a separate display concern.']]},
  {slug:'hp-washing-replacement',category:'progression',title:'HP Washing Replacement',eyebrow:'CHARACTER PROGRESSION',summary:'EverLeaf is designed so mandatory legacy INT washing is not the expected route to viable endgame survivability.',status:'EverLeaf Modified',source:'EverleafMS / SERVER-SYSTEMS',tags:['hp washing','hp','survivability'],sections:[['Design goal','Character survivability should come from an intentional server-designed progression path rather than requiring players to plan years of legacy INT washing.'],['What this means','Quality-of-life removes the historical burden without making survivability meaningless. Exact progression mechanics should always be documented as the implementation evolves.']]},
  {slug:'trade-button-free-market',category:'systems',title:'Trade Button → Free Market',eyebrow:'QUALITY OF LIFE',summary:'EverLeaf repurposes the classic Trade/MTS-style button as a convenient route to the Free Market.',status:'EverLeaf Modified',source:'EverleafMS / SERVER-SYSTEMS',tags:['free market','trade','qol'],sections:[['Destination','The intended destination is Free Market map 910000000.'],['How it works','The server-side EnterMTS handler owns the behavior and applies the required guards. A dedicated client patch is not inherently required for the basic button-to-FM behavior.']]},
  {slug:'nx-reward-sources',category:'rewards',title:'NX Reward Sources',eyebrow:'FAIR REWARDS',summary:'EverLeaf distributes NX through repeatable gameplay and verified community actions while keeping reward delivery server-authoritative.',status:'EverLeaf Modified',source:'EverleafMS / SERVER-SYSTEMS',tags:['nx','vote','playtime','daily'],facts:[['Daily reward','1,000 NX'],['7-day streak','+1,000 NX'],['Playtime','500 NX / 30 min'],['Playtime daily cap','2,000 NX'],['Verified vote','1,500 NX']],sections:[['Safety model','Reward processing is designed around validation, transactional handling, idempotency, and abuse caps so retries cannot silently double-grant currency.'],['Non-P2W principle','NX systems should support cosmetics, convenience, and fair rewards without becoming mandatory competitive progression.']]},
  {slug:'everleaf-launcher',category:'launcher',title:'EverLeaf Launcher',eyebrow:'PLAYER SETUP',summary:'The launcher is the intended way to install, verify, repair, update, and start EverLeaf without manually maintaining client files.',status:'EverLeaf System',source:'EverleafMS / LAUNCHER-PATCHER + CMS-WEB',tags:['launcher','patcher','updates','client'],sections:[['Player workflow','Players should launch EverLeaf through the launcher rather than running the client executable directly. The launcher owns update and integrity workflows.'],['Release management','Website downloads should reference versioned launcher/client releases instead of ad-hoc mutable files.'],['Future integration','The CMS can surface release manifests, current version, patch notes, rollout state, and launcher health without exposing private deployment secrets.']]},
  {slug:'world-channels',category:'world',title:'World Channels',eyebrow:'WORLD TOPOLOGY',summary:'EverLeaf channel information should always come from the authoritative live configuration instead of being independently hardcoded into the website.',status:'Live-derived',source:'EverleafMS / CMS-WEB + SERVER-SYSTEMS',tags:['channels','world','status'],sections:[['Why this matters','A historical website display drifted because it showed a channel count from older configuration. The durable rule is to derive channel/world information from one authoritative source.'],['Current UI rule','Public status can show world/channel availability and player count, but should avoid exposing private host details.']]},
  {slug:'fast-transportation',category:'world',title:'Faster Transportation',eyebrow:'QUALITY OF LIFE',summary:'EverLeaf deliberately reduces long legacy travel waits instead of preserving them purely for nostalgia.',status:'EverLeaf Modified',source:'EverleafMS / SERVER-SYSTEMS',tags:['travel','transport','qol'],sections:[['Design direction','Previously preserved policy uses approximately one-second or instant-style travel for relevant legacy transports.'],['Reasoning','The goal is to remove waiting that adds little gameplay value while preserving the world, destinations, and progression around travel.']]},
  {slug:'pet-vac',category:'systems',title:'Pet Vac',eyebrow:'EVERLEAF FEATURE',summary:'Pet Vac is part of the intended EverLeaf feature set and spans both client presentation and server-authoritative item pickup rules.',status:'EverLeaf System',source:'EverleafMS / SERVER-SYSTEMS',tags:['pet vac','pets','items'],sections:[['System boundary','Pet Vac touches client packets, pet state, map item pickup, ownership validation, and anti-abuse behavior. It should be treated as a subsystem rather than a simple cosmetic toggle.'],['Authority','Item ownership and pickup authorization remain server-side even when client behavior is customized.']]},
  {slug:'rooted-content',category:'systems',title:'Rooted Content',eyebrow:'CUSTOM CONTENT',summary:'Rooted is an EverLeaf content family that includes Rooted Zakum, materials, and related encounters.',status:'EverLeaf Custom',source:'EverleafMS / SERVER-SYSTEMS',tags:['rooted','zakum','boss','custom'],sections:[['Known scope','The durable library currently records Rooted Zakum, Rooted materials, and Rooted encounters as intended EverLeaf systems.'],['Wiki expansion','As mechanics are validated, this page will expand into requirements, encounters, drop tables, materials, and progression links.']]},
  {slug:'adventurer-jobs',category:'classes',title:'Adventurer Job Families',eyebrow:'JOBS & CLASSES',summary:'Beginner advances into the five classic Adventurer families: Warrior, Magician, Bowman, Thief, and Pirate.',status:'Classic v83',source:'EverLeaf class reference',tags:['warrior','magician','bowman','thief','pirate','beginner'],sections:[['Warrior','Fighter → Crusader → Hero; Page → White Knight → Paladin; Spearman → Dragon Knight → Dark Knight.'],['Magician','Fire/Poison and Ice/Lightning Wizard paths advance through Mage to Arch Mage; Cleric advances to Priest and Bishop.'],['Bowman','Hunter → Ranger → Bow Master; Crossbowman → Sniper → Marksman.'],['Thief','Assassin → Hermit → Night Lord; Bandit → Chief Bandit → Shadower.'],['Pirate','Brawler → Marauder → Buccaneer; Gunslinger → Outlaw → Corsair.']]}
];
const bySlug=new Map(entries.map(entry=>[entry.slug,entry]));
function searchEntries(query='',category='all'){
  const q=String(query||'').trim().toLowerCase();
  return entries.filter(entry=>{
    if(category&&category!=='all'&&entry.category!==category)return false;
    if(!q)return true;
    const hay=[entry.title,entry.summary,entry.status,entry.source,...(entry.tags||[]),...(entry.sections||[]).flat()].join(' ').toLowerCase();
    return hay.includes(q);
  });
}
module.exports={categories,entries,bySlug,searchEntries};
