const categories=[
  {key:'classes',label:'Jobs & Classes',description:'Job families, advancement paths, and class-specific EverLeaf notes.'},
  {key:'progression',label:'Progression',description:'Leveling, post-200 progression, survivability, and long-term goals.'},
  {key:'systems',label:'Gameplay & QoL',description:'EverLeaf-specific quality-of-life features and gameplay systems.'},
  {key:'rewards',label:'NX & Rewards',description:'Non-P2W reward sources, voting, playtime, and NX information.'},
  {key:'launcher',label:'Launcher & Client',description:'Install, update, repair, widescreen, and client troubleshooting.'},
  {key:'world',label:'World & Travel',description:'Channels, Free Market, transportation, and world navigation.'},
  {key:'content',label:'Bosses & Custom Content',description:'EverLeaf encounters, custom content, and content currently being expanded.'},
];

const sourceDocs={
  project:'PROJECT-DESIGN.md',
  systems:'SERVER-SYSTEMS.md',
  cms:'CMS-WEB.md',
  launcher:'LAUNCHER-PATCHER.md',
  qol:'QOL-KNOWN-ISSUES.md',
  maps:'NPC-MAPS.md',
  nx:'CUSTOM-NX-CASH.md'
};

const entry=(data)=>({
  verification:'Player-facing EverLeaf reference',
  source:'EverLeaf Player Wiki',
  sourceDoc:'EverLeaf live configuration',
  status:'Player Guide',
  tags:[],
  facts:[],
  sections:[],
  ...data
});

const entries=[
  entry({slug:'enhanced-classic',category:'systems',title:'Welcome to EverLeaf',eyebrow:'START HERE',summary:'EverLeaf is an Enhanced Classic MapleStory v83 server: familiar early MapleStory at its core, with modern quality-of-life, longer progression, and no pay-to-win advantage.',tags:['v83','classic','everleaf','start'],facts:[['Client','v83'],['Level cap','250'],['Channels','20 configured'],['Pay-to-win','No']],sections:[['What stays classic','The world, job identity, early MapleStory feel, familiar maps, quests, bosses, items, and social progression remain the foundation.'],['What EverLeaf changes','EverLeaf adds a level-250 progression path, removes the need for mandatory legacy HP washing, shortens unnecessary travel waits, adds launcher-managed updates, supports custom content, and continues expanding quality-of-life systems.'],['Development status','EverLeaf is still being actively developed. The Wiki is intended to track player-facing behavior as systems are completed and verified.']]}),
  entry({slug:'getting-started',category:'systems',title:'Getting Started',eyebrow:'NEW PLAYER GUIDE',summary:'Create an account, install through the EverLeaf Launcher, enter Maple World, choose your job direction, and use the Wiki as your server-specific reference.',tags:['new player','account','launcher','beginner'],facts:[['Recommended launch method','EverLeaf Launcher'],['Starting class','Beginner']],sections:[['1. Create your account','Use the website registration flow when registration is open. Keep your account credentials private and use a unique password.'],['2. Install and update','Download and run the EverLeaf Launcher. Let it verify and update the client before pressing Play.'],['3. Start your character','New characters begin as Beginners and can move into the supported classic and special job families as their advancement content becomes available.'],['4. Use server-specific guides','EverLeaf intentionally differs from stock v83 in progression, transportation, rewards, launcher behavior, and custom content, so use this Wiki for EverLeaf-specific rules.']]}),
  entry({slug:'adventurer-jobs',category:'classes',title:'Adventurer Job Families',eyebrow:'JOBS & CLASSES',summary:'Beginner advances into the five classic Adventurer families: Warrior, Magician, Bowman, Thief, and Pirate.',status:'Classic v83',verification:'Classic job paths used by EverLeaf',sourceDoc:'EverLeaf class reference',tags:['warrior','magician','bowman','thief','pirate','beginner'],sections:[['Warrior','Fighter → Crusader → Hero; Page → White Knight → Paladin; Spearman → Dragon Knight → Dark Knight.'],['Magician','Fire/Poison and Ice/Lightning Wizard paths advance through Mage to Arch Mage; Cleric advances to Priest and Bishop.'],['Bowman','Hunter → Ranger → Bow Master; Crossbowman → Sniper → Marksman.'],['Thief','Assassin → Hermit → Night Lord; Bandit → Chief Bandit → Shadower.'],['Pirate','Brawler → Marauder → Buccaneer; Gunslinger → Outlaw → Corsair.']]}),
  entry({slug:'cygnus-knights',category:'classes',title:'Knights of Cygnus',eyebrow:'SPECIAL JOBS',summary:'The Cygnus family includes Dawn Warrior, Blaze Wizard, Wind Archer, Night Walker, and Thunder Breaker.',tags:['cygnus','dawn warrior','blaze wizard','wind archer','night walker','thunder breaker'],sections:[['The five branches','Dawn Warrior is the warrior branch, Blaze Wizard the magician branch, Wind Archer the bow branch, Night Walker the thief branch, and Thunder Breaker the pirate branch.'],['EverLeaf status','Cygnus characters are represented in the live game database and public rankings. Individual quest and skill parity continues to be validated as EverLeaf develops.']]}),
  entry({slug:'aran-guide',category:'classes',title:'Aran',eyebrow:'SPECIAL JOBS',summary:'Aran is EverLeaf’s polearm-focused hero class, built around combo-driven combat and its classic progression identity.',tags:['aran','polearm','combo','legend'],sections:[['Class identity','Aran uses polearms and a combo-oriented combat style distinct from the five Adventurer families.'],['EverLeaf status','Aran is represented by the current client/server class set and rankings. Server-specific changes will be documented here as they are verified.']]}),
  entry({slug:'evan-guide',category:'classes',title:'Evan',eyebrow:'SPECIAL JOBS',summary:'Evan is the Dragon Master class, progressing alongside Mir through its multi-stage advancement structure.',tags:['evan','mir','dragon master','magic'],sections:[['Class identity','Evan fights with magic while Mir grows through the class progression. Its advancement structure differs from standard four-job Adventurers.'],['EverLeaf status','Evan support is part of the active EverLeaf class work. Only behavior confirmed on the live server should be treated as final while the implementation is still being completed.']]}),
  entry({slug:'level-250-progression',category:'progression',title:'Level 250 Progression',eyebrow:'PROGRESSION',summary:'EverLeaf extends character progression beyond the classic level-200 endpoint and targets a level cap of 250.',sourceDoc:sourceDocs.systems,tags:['level 250','exp','post-200','level cap'],facts:[['Level cap','250']],sections:[['Beyond level 200','EverLeaf keeps leveling meaningful after the classic level-200 milestone instead of ending character progression there.'],['EXP handling','Post-200 EXP is handled server-side so the game database remains authoritative even when client UI needs additional compatibility work.'],['Endgame direction','The extended cap is intended to support a longer progression arc and EverLeaf-specific endgame content.']]}),
  entry({slug:'hp-washing-replacement',category:'progression',title:'No Mandatory HP Washing',eyebrow:'SURVIVABILITY',summary:'EverLeaf is designed so players do not need the old INT-washing routine just to make a normal character viable later.',sourceDoc:sourceDocs.systems,tags:['hp washing','hp','survivability','qol'],facts:[['Mandatory legacy HP washing','No']],sections:[['Design goal','Normal character progression should provide a reasonable route to survivability without requiring players to sabotage early stat builds for future HP.'],['What to expect','Survivability still matters, but EverLeaf’s direction is to solve it through intentional server progression rather than mandatory legacy washing.']]}),
  entry({slug:'nx-reward-sources',category:'rewards',title:'NX Reward Sources',eyebrow:'NX & REWARDS',summary:'EverLeaf provides repeatable non-P2W ways to earn NX through participation and verified community actions.',sourceDoc:sourceDocs.systems,tags:['nx','vote','playtime','daily'],facts:[['Daily reward','1,000 NX'],['7-day streak','+1,000 NX'],['Playtime','500 NX / 30 min'],['Playtime daily cap','2,000 NX'],['Verified vote','1,500 NX']],sections:[['Daily and streak rewards','The preserved EverLeaf reward policy includes a 1,000 NX daily reward and a 1,000 NX seven-day streak bonus.'],['Playtime rewards','The preserved policy awards 500 NX per 30 minutes of qualifying playtime, capped at 2,000 NX per day.'],['Voting','A verified vote is configured to award 1,500 NX. Reward delivery is server-side so repeated callbacks do not intentionally double-grant the same vote.'],['Fair-play rule','NX is meant to support cosmetics, convenience, and fair rewards without becoming mandatory competitive power.']]}),
  entry({slug:'voting-guide',category:'rewards',title:'Voting for EverLeaf',eyebrow:'COMMUNITY REWARDS',summary:'Verified votes can reward NX while helping EverLeaf visibility. The server validates the vote before credit is granted.',sourceDoc:sourceDocs.systems,tags:['vote','nx','gtop100'],facts:[['Verified vote reward','1,500 NX']],sections:[['How rewards work','Vote rewards are tied to a verified provider callback and the matching EverLeaf account.'],['If NX does not appear','Do not repeatedly spam the vote flow. Check that you used the correct account name and allow the verified callback to process; staff can investigate failed delivery without manually duplicating rewards.']]}),
  entry({slug:'pet-vac',category:'systems',title:'Pet Vac',eyebrow:'QUALITY OF LIFE',summary:'Pet Vac is part of the EverLeaf feature set and is designed to make pet looting less tedious while keeping item ownership checks server-side.',sourceDoc:sourceDocs.systems,tags:['pet vac','pets','loot','qol'],sections:[['What it changes','Pet Vac expands the convenience of pet item pickup compared with strict classic looting behavior.'],['What it does not change','The server still decides whether an item can be picked up and who owns it. Pet Vac is convenience, not a bypass around ownership or anti-abuse rules.']]}),
  entry({slug:'trade-button-free-market',category:'world',title:'Trade Button → Free Market',eyebrow:'WORLD TRAVEL',summary:'EverLeaf repurposes the classic Trade/MTS-style button as a fast route to the Free Market.',sourceDoc:sourceDocs.systems,tags:['free market','trade','travel','qol'],facts:[['Destination map','910000000']],sections:[['Where it goes','The EverLeaf Trade button route targets Free Market map 910000000.'],['Why','It keeps a familiar client control useful without forcing players through unnecessary travel just to reach the market hub.']]}),
  entry({slug:'fast-transportation',category:'world',title:'Faster Transportation',eyebrow:'WORLD TRAVEL',summary:'EverLeaf shortens long legacy transportation waits while keeping the world and destination structure recognizable.',sourceDoc:sourceDocs.systems,tags:['travel','transport','qol'],sections:[['Design direction','Relevant legacy transports are intended to use very short waits rather than preserving long idle travel times solely for nostalgia.'],['What stays intact','Destinations, world geography, and travel NPCs still matter; the goal is to remove downtime, not flatten Maple World into one menu.']]}),
  entry({slug:'world-channels',category:'world',title:'Channels & Server Status',eyebrow:'LIVE WORLD',summary:'EverLeaf currently uses 20 configured channels, and the website status panel reads the live server configuration instead of a separate hard-coded count.',sourceDoc:sourceDocs.cms,tags:['channels','server status','online'],facts:[['Configured channels','20']],sections:[['Live status','The homepage and deployment health checks read the configured channel set and server status directly.'],['Why counts can change','If the live server configuration changes later, the public status system should follow that authoritative configuration rather than requiring a separate website edit.']]}),
  entry({slug:'everleaf-launcher',category:'launcher',title:'Installing EverLeaf',eyebrow:'LAUNCHER & CLIENT',summary:'Use the EverLeaf Launcher to install, update, verify, repair, and start the game.',sourceDoc:sourceDocs.launcher,tags:['launcher','install','patcher','client'],facts:[['Recommended entry point','EverLeaf Launcher']],sections:[['Install','Get the launcher from the Downloads page and keep the game in a folder your Windows account can write to normally.'],['Update','Open the launcher before playing so it can compare your managed client files with the current release.'],['Play','Use the launcher Play action after verification completes. Launching an old client executable directly can leave you on mismatched files.']]}),
  entry({slug:'launcher-repair-updates',category:'launcher',title:'Repairing or Updating the Client',eyebrow:'LAUNCHER HELP',summary:'The launcher is designed to detect missing or changed managed files and safely replace only what the current EverLeaf release requires.',sourceDoc:sourceDocs.launcher,tags:['repair','update','launcher','files'],sections:[['Repair mode','Repair compares managed files against the release manifest and redownloads files that are missing or fail integrity checks.'],['Interrupted updates','Updates are designed around staged downloads and validation so an interrupted patch does not intentionally activate half-finished files.'],['When to repair','Use Repair when the client stops launching after a file change, an update was interrupted, or the launcher reports missing/corrupt managed files.']]}),
  entry({slug:'widescreen-support',category:'launcher',title:'Widescreen & Resolution',eyebrow:'CLIENT DISPLAY',summary:'EverLeaf includes widescreen work, but a resolution is only considered supported when rendering, UI placement, and click/input geometry all behave correctly.',sourceDoc:sourceDocs.qol,tags:['widescreen','resolution','ui','client'],sections:[['What is being improved','EverLeaf client work covers larger rendering areas together with UI placement and interaction fixes.'],['Report display bugs','If a button looks correct but clicks in the wrong place, a special map UI is shifted, or a panel is cut off, report the exact resolution and screen where it happens.']]}),
  entry({slug:'rankings-guide',category:'systems',title:'Live Player Rankings',eyebrow:'WEBSITE GUIDE',summary:'The Rankings page reads real saved characters from the game MySQL database and displays each player’s saved character appearance.',tags:['rankings','players','levels','avatars'],facts:[['Source','Live game MySQL'],['GM characters','Excluded'],['Banned accounts','Excluded']],sections:[['What is ranked','The public board sorts by level, then current EXP, fame, and character name for stable tie-breaking.'],['Character portraits','Rankings use the character’s saved skin, face, hair, and visible equipped item IDs to render the player instead of showing a generic class mascot.'],['When it updates','Refreshing the page re-queries saved character progression. Character portraits are cached briefly for performance, so a freshly changed outfit may take a few minutes to refresh.']]}),
  entry({slug:'rooted-content',category:'content',title:'Rooted Content',eyebrow:'CUSTOM EVERLEAF CONTENT',summary:'Rooted is an EverLeaf custom-content family that includes Rooted Zakum, related materials, and encounter work.',sourceDoc:sourceDocs.systems,tags:['rooted','zakum','boss','custom'],sections:[['Current scope','The project currently tracks Rooted Zakum, Rooted materials, and related encounter systems.'],['Wiki policy','Requirements, mechanics, drops, and progression links will be added here only as those details are validated for the live server rather than guessed from development notes.']]}),
  entry({slug:'wiki-how-to-use',category:'systems',title:'How to Use This Wiki',eyebrow:'EVERLEAF WIKI',summary:'This Wiki is for player-facing EverLeaf behavior. Staff can update articles from the CMS without waiting for a code deployment.',tags:['wiki','guides','help'],sections:[['Player-facing first','The public Wiki focuses on how to play EverLeaf: classes, progression, rewards, travel, launcher help, and verified custom content. Internal implementation notes should not be public guides.'],['Living articles','Published articles live in the site CMS. Staff can edit, draft, review, and publish changes as the server evolves.'],['Accuracy rule','When a feature is still being built, the article should say so instead of presenting planned mechanics as already live.']]})
];

const bySlug=new Map(entries.map(item=>[item.slug,item]));

function searchEntries(query='',category='all'){
  const q=String(query||'').trim().toLowerCase();
  return entries.filter(item=>{
    if(category!=='all'&&item.category!==category)return false;
    if(!q)return true;
    const haystack=[item.title,item.summary,item.eyebrow,item.status,item.source,item.sourceDoc,...(item.tags||[]),...(item.sections||[]).flat(),...(item.facts||[]).flat()].join(' ').toLowerCase();
    return haystack.includes(q);
  });
}

module.exports={categories,sourceDocs,entries,bySlug,searchEntries};
